Irisデータに対してLeave-one-out cross-validationやK-fold cross-validationを行ってみる。

In [116]:
import sys
from sklearn.datasets import load_iris
import pandas as pd
from sklearn.model_selection import KFold, ShuffleSplit, GroupKFold, StratifiedKFold, StratifiedShuffleSplit
from sklearn import svm
print(sys.version_info)

sys.version_info(major=3, minor=6, micro=2, releaselevel='final', serial=0)


digits (DeepLearningの練習としてよく使われる数字判定のデータ) の読み込み

In [44]:
digits = datasets.load_digits()

X = pd.DataFrame(digits.data)
y = digits.target

k=5, すわわちデータを5分割してみる。

In [52]:
k_fold = KFold(n_splits=5)

k_fold.split(X)とすることでデータを5分割し、各グループのインデックスを与える。<br>
k_fold.splitはランダムではなくクラスの比率を同じにすることもない。

In [53]:
for train_indices, test_indices in k_fold.split(X):
    print(train_indices, test_indices)

[ 360  361  362 ..., 1794 1795 1796] [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 2

In [9]:
test_indices

array([113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149])

In [58]:
len(X.index)

1797

[kFold](http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.KFold.html#sklearn.model_selection.KFold)を使うことでfoldを作成し、TrainingとTestに分割することができる。<br>
ランダムに分割したい場合はrandom_state=None, shuffle=Trueとする。

In [95]:
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
y = np.array([1, 2, 1, 2, 1, 2])
k_fold = KFold(n_splits=3)
for train_index, test_index in k_fold.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
k_fold = KFold(n_splits=3, random_state=None, shuffle=True)
print()
for train_index, test_index in k_fold.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)    


TRAIN: [2 3 4 5] TEST: [0 1]
TRAIN: [0 1 4 5] TEST: [2 3]
TRAIN: [0 1 2 3] TEST: [4 5]

TRAIN: [0 2 3 5] TEST: [1 4]
TRAIN: [0 1 3 4] TEST: [2 5]
TRAIN: [1 2 4 5] TEST: [0 3]


[ShuffleSplit](http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.ShuffleSplit.html#sklearn.model_selection.ShuffleSplit)を使ってもランダムにfoldを作成し、TrainingとTestに分割することができる。<br>
乱数を固定したくない場合はrandom_state=Noneとする。

In [96]:
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
y = np.array([1, 2, 1, 2, 1, 2])
rs = ShuffleSplit(n_splits=3, random_state=None, test_size=0.5, train_size=None)
for train_index, test_index in rs.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)


TRAIN: [5 0 1] TEST: [2 4 3]
TRAIN: [2 5 0] TEST: [3 1 4]
TRAIN: [3 5 4] TEST: [1 2 0]


[GroupKFold](http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GroupKFold.html#sklearn.model_selection.GroupKFold)を使うと必ず同じfoldに入るためのグループを作ることができる。<br>
例えば以下の例では0, 1番目のデータ、2, 3番目のデータはそれぞれ必ず同じfoldに分類される。

In [104]:
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
y = np.array([1, 2, 1, 2, 1, 2])
skf = Stgroup_kfold = GroupKFold(n_splits=2)
group_kfold.get_n_splits(X, y, groups)
print(group_kfold)
for train_index, test_index in group_kfold.split(X, y, groups):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print(X_train, X_test, y_train, y_test)


GroupKFold(n_splits=2)
TRAIN: [2 3] TEST: [0 1]
[[5 6]
 [7 8]] [[1 2]
 [3 4]] [3 4] [1 2]
TRAIN: [0 1] TEST: [2 3]
[[1 2]
 [3 4]] [[5 6]
 [7 8]] [1 2] [3 4]


[StratifiedKFold](http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.StratifiedKFold.html#sklearn.model_selection.StratifiedKFold)を使うと目的変数のクラスごとの割合を考慮してfoldを作成することができる。<br>以下の例では<br>y=1であるインデックス番号0, 1, 2, 3、<br>y=2であるインデックス番号4, 5, 6, 7<br>から半分ずつ取り出しTrainingとし、残りをTestとしfoldを作成している。<br>
ランダムに分割したい場合はrandom_state=None, shuffle=Trueとする。

In [115]:
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [13, 14], [15, 16]])
y = np.array([1, 1, 1, 1, 2, 2, 2, 2])
skf = StratifiedKFold(n_splits=2)
for train_index, test_index in skf.split(X, y):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
print()
skf = StratifiedKFold(n_splits=4, random_state=None, shuffle=True)
for train_index, test_index in skf.split(X, y):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]    

TRAIN: [2 3 6 7] TEST: [0 1 4 5]
TRAIN: [0 1 4 5] TEST: [2 3 6 7]

TRAIN: [0 1 3 4 6 7] TEST: [2 5]
TRAIN: [1 2 3 5 6 7] TEST: [0 4]
TRAIN: [0 1 2 4 5 7] TEST: [3 6]
TRAIN: [0 2 3 4 5 6] TEST: [1 7]


[StratifiedShuffleSplit](http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.StratifiedShuffleSplit.html#sklearn.model_selection.StratifiedShuffleSplit)を使ってもランダムにfoldを作成し、TrainingとTestに分割することができる。<br>
乱数を固定したくない場合はrandom_state=Noneとする。

In [111]:
>>> from sklearn.model_selection import StratifiedShuffleSplit
>>> X = np.array([[1, 2], [3, 4], [1, 2], [3, 4]])
>>> y = np.array([0, 0, 1, 1])
>>> sss = StratifiedShuffleSplit(n_splits=3, test_size=0.5, random_state=0)
>>> sss.get_n_splits(X, y)
3
>>> print(sss)       
StratifiedShuffleSplit(n_splits=3, random_state=0, ...)
>>> for train_index, test_index in sss.split(X, y):
...    print("TRAIN:", train_index, "TEST:", test_index)
...    X_train, X_test = X[train_index], X[test_index]
...    y_train, y_test = y[train_index], y[test_index]
TRAIN: [1 2] TEST: [3 0]
TRAIN: [0 2] TEST: [1 3]
TRAIN: [0 2] TEST: [3 1]

0.97999999999999998

[LeaveOneOut](http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.LeaveOneOut.html#sklearn.model_selection.LeaveOneOut)を使うことでデータセットのサンプル一つずつをTestとすることができる。

In [ ]:
from sklearn.model_selection import LeaveOneOut
>>> X = np.array([[1, 2], [3, 4]])
>>> y = np.array([1, 2])
>>> loo = LeaveOneOut()
>>> loo.get_n_splits(X)
2
>>> print(loo)
LeaveOneOut()
>>> for train_index, test_index in loo.split(X):
...    print("TRAIN:", train_index, "TEST:", test_index)
...    X_train, X_test = X[train_index], X[test_index]
...    y_train, y_test = y[train_index], y[test_index]
...    print(X_train, X_test, y_train, y_test)
TRAIN: [1] TEST: [0]
[[3 4]] [[1 2]] [2] [1]
TRAIN: [0] TEST: [1]
[[1 2]] [[3 4]] [1] [2]

In [34]:
df = pd.DataFrame(X_digits)

In [22]:
import numpy as np
X_folds = np.array_split(X_digits, 3)
y_folds = np.array_split(y_digits, 3)
scores = list()
for k in range(3):
    X_train = list(X_folds)
    X_test  = X_train.pop(k)
    X_train = np.concatenate(X_train)
    y_train = list(y_folds)
    y_test  = y_train.pop(k)
    y_train = np.concatenate(y_train)
    scores.append(svc.fit(X_train, y_train).score(X_test, y_test))
print(scores)

NameError: name 'svc' is not defined

In [32]:
X_digits[np.array([1, 2, 3])]

array([[  0.,   0.,   0.,  12.,  13.,   5.,   0.,   0.,   0.,   0.,   0.,
         11.,  16.,   9.,   0.,   0.,   0.,   0.,   3.,  15.,  16.,   6.,
          0.,   0.,   0.,   7.,  15.,  16.,  16.,   2.,   0.,   0.,   0.,
          0.,   1.,  16.,  16.,   3.,   0.,   0.,   0.,   0.,   1.,  16.,
         16.,   6.,   0.,   0.,   0.,   0.,   1.,  16.,  16.,   6.,   0.,
          0.,   0.,   0.,   0.,  11.,  16.,  10.,   0.,   0.],
       [  0.,   0.,   0.,   4.,  15.,  12.,   0.,   0.,   0.,   0.,   3.,
         16.,  15.,  14.,   0.,   0.,   0.,   0.,   8.,  13.,   8.,  16.,
          0.,   0.,   0.,   0.,   1.,   6.,  15.,  11.,   0.,   0.,   0.,
          1.,   8.,  13.,  15.,   1.,   0.,   0.,   0.,   9.,  16.,  16.,
          5.,   0.,   0.,   0.,   0.,   3.,  13.,  16.,  16.,  11.,   5.,
          0.,   0.,   0.,   0.,   3.,  11.,  16.,   9.,   0.],
       [  0.,   0.,   7.,  15.,  13.,   1.,   0.,   0.,   0.,   8.,  13.,
          6.,  15.,   4.,   0.,   0.,   0.,   2.,   1.,  13.

In [31]:
np.array([1, 2, 3])

array([1, 2, 3])

In [36]:
df

0    1     2     3     4     5     6    7    8     9  ...     54   55  \
0     0.0  0.0   5.0  13.0   9.0   1.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
1     0.0  0.0   0.0  12.0  13.0   5.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
2     0.0  0.0   0.0   4.0  15.0  12.0   0.0  0.0  0.0   0.0 ...    5.0  0.0   
3     0.0  0.0   7.0  15.0  13.0   1.0   0.0  0.0  0.0   8.0 ...    9.0  0.0   
4     0.0  0.0   0.0   1.0  11.0   0.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
5     0.0  0.0  12.0  10.0   0.0   0.0   0.0  0.0  0.0   0.0 ...    4.0  0.0   
6     0.0  0.0   0.0  12.0  13.0   0.0   0.0  0.0  0.0   0.0 ...    8.0  0.0   
7     0.0  0.0   7.0   8.0  13.0  16.0  15.0  1.0  0.0   0.0 ...    0.0  0.0   
8     0.0  0.0   9.0  14.0   8.0   1.0   0.0  0.0  0.0   0.0 ...    8.0  0.0   
9     0.0  0.0  11.0  12.0   0.0   0.0   0.0  0.0  0.0   2.0 ...    4.0  0.0   
10    0.0  0.0   1.0   9.0  15.0  11.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
11    0.0  0.0   0.0   0.0  14.0  13.0   1.0  0.0  0.0   0.0 ...    0.0  0.0   
12    0.0  0.0   5.0  12.0   1.0   0.0   0.0  0.0  0.0   0.0 ...    8.0  2.0   
13    0.0  2.0   9.0  15.0  14.0   9.0   3.0  0.0  0.0   4.0 ...    6.0  0.0   
14    0.0  0.0   0.0   8.0  15.0   1.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
15    0.0  5.0  12.0  13.0  16.0  16.0   2.0  0.0  0.0  11.0 ...    0.0  0.0   
16    0.0  0.0   0.0   8.0  15.0   1.0   0.0  0.0  0.0   0.0 ...   16.0  2.0   
17    0.0  0.0   1.0   8.0  15.0  10.0   0.0  0.0  0.0   3.0 ...    0.0  0.0   
18    0.0  0.0  10.0   7.0  13.0   9.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
19    0.0  0.0   6.0  14.0   4.0   0.0   0.0  0.0  0.0   0.0 ...   16.0  2.0   
20    0.0  0.0   3.0  13.0  11.0   7.0   0.0  0.0  0.0   0.0 ...    1.0  0.0   
21    0.0  0.0   0.0   2.0  16.0  16.0   2.0  0.0  0.0   0.0 ...    2.0  0.0   
22    0.0  0.0   8.0  16.0   5.0   0.0   0.0  0.0  0.0   1.0 ...    3.0  0.0   
23    0.0  1.0   8.0  12.0  15.0  14.0   4.0  0.0  0.0   3.0 ...    0.0  0.0   
24    0.0  0.0   0.0   0.0  12.0   2.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
25    0.0  0.0  12.0   8.0   8.0   7.0   0.0  0.0  0.0   3.0 ...    0.0  0.0   
26    0.0  0.0   1.0  13.0  14.0   3.0   0.0  0.0  0.0   0.0 ...   12.0  0.0   
27    0.0  0.0   0.0   8.0  14.0  14.0   2.0  0.0  0.0   0.0 ...    0.0  0.0   
28    0.0  0.0  10.0  11.0   4.0   0.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
29    0.0  0.0   9.0  13.0   7.0   0.0   0.0  0.0  0.0   0.0 ...   16.0  2.0   
...   ...  ...   ...   ...   ...   ...   ...  ...  ...   ... ...    ...  ...   
1767  0.0  0.0   0.0   2.0  16.0   1.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
1768  0.0  0.0   5.0  16.0  10.0   0.0   0.0  0.0  0.0   0.0 ...    5.0  0.0   
1769  0.0  0.0   9.0  12.0  14.0   6.0   0.0  0.0  0.0   0.0 ...    2.0  0.0   
1770  0.0  2.0  10.0  12.0  16.0   8.0   0.0  0.0  0.0   4.0 ...    5.0  0.0   
1771  0.0  0.0   0.0   6.0  12.0   6.0   0.0  0.0  0.0   0.0 ...   12.0  0.0   
1772  0.0  0.0   5.0  14.0  11.0   8.0   0.0  0.0  0.0   4.0 ...    0.0  0.0   
1773  0.0  0.0   2.0  13.0  10.0   0.0   0.0  0.0  0.0   0.0 ...   12.0  0.0   
1774  0.0  0.0   6.0  12.0  12.0   6.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
1775  0.0  0.0   6.0  16.0  16.0   3.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
1776  0.0  0.0  12.0  16.0  16.0   7.0   0.0  0.0  0.0   3.0 ...    7.0  0.0   
1777  0.0  0.0   0.0   2.0  14.0   0.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
1778  0.0  0.0   0.0   1.0  13.0   8.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
1779  0.0  0.0   3.0  10.0  16.0  16.0   4.0  0.0  0.0   0.0 ...    0.0  0.0   
1780  0.0  3.0  14.0  15.0   6.0   0.0   0.0  0.0  0.0   7.0 ...    6.0  0.0   
1781  0.0  0.0  10.0  16.0  14.0   5.0   0.0  0.0  0.0   2.0 ...    1.0  0.0   
1782  0.0  1.0  10.0  13.0   2.0   0.0   0.0  0.0  0.0  10.0 ...   13.0  0.0   
1783  0.0  0.0  15.0  13.0   1.0   0.0   0.0  0.0  0.0   0.0 ...   14.0  0.0   
1784  0.0  0.0   1.0  10.0  14.0  13.0   1.0  0.0  0.0   0.0 ...    2.0  0.0   
1785  0

In [39]:
df.ix[np.array([0,2,3]), :] # 範囲指定


0    1    2     3     4     5    6    7    8    9  ...    54   55   56  \
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0 ...   5.0  0.0  0.0   
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0 ...   9.0  0.0  0.0   

    57   58    59    60    61   62   63  
0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
2  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3  0.0  7.0  13.0  13.0   9.0  0.0  0.0  

[3 rows x 64 columns]

In [41]:
df

0    1     2     3     4     5     6    7    8     9  ...     54   55  \
0     0.0  0.0   5.0  13.0   9.0   1.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
1     0.0  0.0   0.0  12.0  13.0   5.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
2     0.0  0.0   0.0   4.0  15.0  12.0   0.0  0.0  0.0   0.0 ...    5.0  0.0   
3     0.0  0.0   7.0  15.0  13.0   1.0   0.0  0.0  0.0   8.0 ...    9.0  0.0   
4     0.0  0.0   0.0   1.0  11.0   0.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
5     0.0  0.0  12.0  10.0   0.0   0.0   0.0  0.0  0.0   0.0 ...    4.0  0.0   
6     0.0  0.0   0.0  12.0  13.0   0.0   0.0  0.0  0.0   0.0 ...    8.0  0.0   
7     0.0  0.0   7.0   8.0  13.0  16.0  15.0  1.0  0.0   0.0 ...    0.0  0.0   
8     0.0  0.0   9.0  14.0   8.0   1.0   0.0  0.0  0.0   0.0 ...    8.0  0.0   
9     0.0  0.0  11.0  12.0   0.0   0.0   0.0  0.0  0.0   2.0 ...    4.0  0.0   
10    0.0  0.0   1.0   9.0  15.0  11.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
11    0.0  0.0   0.0   0.0  14.0  13.0   1.0  0.0  0.0   0.0 ...    0.0  0.0   
12    0.0  0.0   5.0  12.0   1.0   0.0   0.0  0.0  0.0   0.0 ...    8.0  2.0   
13    0.0  2.0   9.0  15.0  14.0   9.0   3.0  0.0  0.0   4.0 ...    6.0  0.0   
14    0.0  0.0   0.0   8.0  15.0   1.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
15    0.0  5.0  12.0  13.0  16.0  16.0   2.0  0.0  0.0  11.0 ...    0.0  0.0   
16    0.0  0.0   0.0   8.0  15.0   1.0   0.0  0.0  0.0   0.0 ...   16.0  2.0   
17    0.0  0.0   1.0   8.0  15.0  10.0   0.0  0.0  0.0   3.0 ...    0.0  0.0   
18    0.0  0.0  10.0   7.0  13.0   9.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
19    0.0  0.0   6.0  14.0   4.0   0.0   0.0  0.0  0.0   0.0 ...   16.0  2.0   
20    0.0  0.0   3.0  13.0  11.0   7.0   0.0  0.0  0.0   0.0 ...    1.0  0.0   
21    0.0  0.0   0.0   2.0  16.0  16.0   2.0  0.0  0.0   0.0 ...    2.0  0.0   
22    0.0  0.0   8.0  16.0   5.0   0.0   0.0  0.0  0.0   1.0 ...    3.0  0.0   
23    0.0  1.0   8.0  12.0  15.0  14.0   4.0  0.0  0.0   3.0 ...    0.0  0.0   
24    0.0  0.0   0.0   0.0  12.0   2.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
25    0.0  0.0  12.0   8.0   8.0   7.0   0.0  0.0  0.0   3.0 ...    0.0  0.0   
26    0.0  0.0   1.0  13.0  14.0   3.0   0.0  0.0  0.0   0.0 ...   12.0  0.0   
27    0.0  0.0   0.0   8.0  14.0  14.0   2.0  0.0  0.0   0.0 ...    0.0  0.0   
28    0.0  0.0  10.0  11.0   4.0   0.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
29    0.0  0.0   9.0  13.0   7.0   0.0   0.0  0.0  0.0   0.0 ...   16.0  2.0   
...   ...  ...   ...   ...   ...   ...   ...  ...  ...   ... ...    ...  ...   
1767  0.0  0.0   0.0   2.0  16.0   1.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
1768  0.0  0.0   5.0  16.0  10.0   0.0   0.0  0.0  0.0   0.0 ...    5.0  0.0   
1769  0.0  0.0   9.0  12.0  14.0   6.0   0.0  0.0  0.0   0.0 ...    2.0  0.0   
1770  0.0  2.0  10.0  12.0  16.0   8.0   0.0  0.0  0.0   4.0 ...    5.0  0.0   
1771  0.0  0.0   0.0   6.0  12.0   6.0   0.0  0.0  0.0   0.0 ...   12.0  0.0   
1772  0.0  0.0   5.0  14.0  11.0   8.0   0.0  0.0  0.0   4.0 ...    0.0  0.0   
1773  0.0  0.0   2.0  13.0  10.0   0.0   0.0  0.0  0.0   0.0 ...   12.0  0.0   
1774  0.0  0.0   6.0  12.0  12.0   6.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
1775  0.0  0.0   6.0  16.0  16.0   3.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
1776  0.0  0.0  12.0  16.0  16.0   7.0   0.0  0.0  0.0   3.0 ...    7.0  0.0   
1777  0.0  0.0   0.0   2.0  14.0   0.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
1778  0.0  0.0   0.0   1.0  13.0   8.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
1779  0.0  0.0   3.0  10.0  16.0  16.0   4.0  0.0  0.0   0.0 ...    0.0  0.0   
1780  0.0  3.0  14.0  15.0   6.0   0.0   0.0  0.0  0.0   7.0 ...    6.0  0.0   
1781  0.0  0.0  10.0  16.0  14.0   5.0   0.0  0.0  0.0   2.0 ...    1.0  0.0   
1782  0.0  1.0  10.0  13.0   2.0   0.0   0.0  0.0  0.0  10.0 ...   13.0  0.0   
1783  0.0  0.0  15.0  13.0   1.0   0.0   0.0  0.0  0.0   0.0 ...   14.0  0.0   
1784  0.0  0.0   1.0  10.0  14.0  13.0   1.0  0.0  0.0   0.0 ...    2.0  0.0   
1785  0

In [ ]:


>>> X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
>>> y = np.array([1, 2, 1, 2])
>>> rs = ShuffleSplit(n_splits=3, test_size=.25, random_state=0)
>>> rs.get_n_splits(X)
3
>>> print(rs)
ShuffleSplit(n_splits=3, random_state=0, test_size=0.25, train_size=None)
>>> for train_index, test_index in rs.split(X):
...    print("TRAIN:", train_index, "TEST:", test_index)
...  
TRAIN: [3 1 0] TEST: [2]
TRAIN: [2 1 3] TEST: [0]
TRAIN: [0 2 1] TEST: [3]
>>> rs = ShuffleSplit(n_splits=3, train_size=0.5, test_size=.25,
...                   random_state=0)
>>> for train_index, test_index in rs.split(X):
...    print("TRAIN:", train_index, "TEST:", test_index)
...  
TRAIN: [3 1] TEST: [2]
TRAIN: [2 1] TEST: [0]
TRAIN: [0 2] TEST: [3]